[".asdf"]
    type = "git-repo"
    url = "https://github.com/asdf-vm/asdf.git"
    refreshPeriod = "72h"
    [".asdf".clone]
        args = ["--branch", "v0.9.0"]

[".files/iterm2_shell_integration"]
    type = "git-repo"
    url = "https://github.com/gnachman/iTerm2-shell-integration.git"
    refreshPeriod = "72h"

[".basher"]
    type = "git-repo"
    url = "https://github.com/basherpm/basher.git"
    refreshPeriod = "72h"
