[".files/iterm2_shell_integration"]
    type = "git-repo"
    url = "https://github.com/gnachman/iTerm2-shell-integration.git"
    refreshPeriod = "72h"

[".basher"]
    type = "git-repo"
    url = "https://github.com/basherpm/basher.git"
    refreshPeriod = "72h"

[".zshrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/zimfw/install/master/src/templates/zshrc"
    refreshPeriod = "72h"

[".zimrc"]
    type = "file"
    url = "https://raw.githubusercontent.com/zimfw/install/master/src/templates/zimrc"
    refreshPeriod = "72h"
