#[tasks.kick-off]
#dependencies = ['brew-all', 'fish-all', 'rustup', 'zim']

[tasks.brew]
script = [
'''
#!/bin/bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
'''
]

[tasks.bundle]
command = 'brew'
args = ['bundle', '--global']

[tasks.gofish]
script = [
    'curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash',
    'gofish init'
]

[tasks.fishes]
command = 'gofish'
args = ['install', 'go', 'helm', 'k9s', 'terraform', 'kubectl', 'devdash']

