[tasks.kickoff]
dependencies = ['brew', 'bundle', 'gofish', 'fishes', 'rustup', 'cargos', 'shells']

[tasks.brew]
script = [
'''
#!/bin/bash
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install.sh)"
'''
]

[tasks.bundle]
command = 'brew'
args = ['bundle', '--global']

[tasks.gofish]
script = [
    'curl -fsSL https://raw.githubusercontent.com/fishworks/gofish/master/scripts/install.sh | bash',
    'gofish init'
]

[tasks.fishes]
command = 'gofish'
args = ['install', 'go', 'helm', 'k9s', 'terraform', 'kubectl', 'devdash']

[tasks.rustup]
script = [
    "curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
]

[tasks.cargos]
command = 'cargo'
args = ['install', '--force', 'wrangler', 'ytop', 'cargo-make', 'xsv']

[tasks.shells]
script = [
    'echo "/usr/local/bin/zsh" | sudo tee -a /etc/shells',
    'echo "/usr/local/bin/fish" | sudo tee -a /etc/shells',
    'echo "/usr/local/bin/bash" | sudo tee -a /etc/shells',
    'curl https://git.io/fisher --create-dirs -sLo ~/.config/fish/functions/fisher.fish',
    'chsh -s /usr/local/bin/fish clakeb'
]
