[tasks.src]
dependencies = ['brew-all', 'gofish-all', 'rustup', 'fisher', 'iterm-tools']

[tasks.brew-update]
command = 'brew'
args = ['update']

[tasks.brew-upgrade]
command = 'brew'
args = ['upgrade']

[tasks.brew-cleanup]
command = 'brew'
args = ['cleanup', '-s']

[tasks.brewfile]
command = 'brew'
args = ['bundle', 'dump', '--global', '-f']

[tasks.brew-all]
dependencies = ['brew-update', 'brew-upgrade', 'brew-cleanup', 'brewfile']

[tasks.gofish-update]
command = 'gofish'
args = ['update']

[tasks.gofish-upgrade]
command = 'gofish'
args = ['upgrade']

[tasks.gofish-cleanup]
command = 'gofish'
args = ['cleanup']

[tasks.gofish-all]
dependencies = ['gofish-update', 'gofish-upgrade', 'gofish-cleanup']

[tasks.rustup]
command = 'rustup'
args = ['update']

[tasks.fisher]
script = [
    '#!/usr/local/bin/fish',
    'eksctl completion fish > ~/.config/.files/my-fishes/completions/eksctl.fish',
    'fisher'
]

[tasks.iterm-tools]
script = ['curl -L https://iterm2.com/shell_integration/install_shell_integration_and_utilities.sh | bash']
